name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "phi-helper-work" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build production app
        run: |
          cd bronxworks-program-closure
          npm ci
          npm run build

      - name: Install and build POC app
        run: |
          cd bronxworks-closeout-poc
          npm ci
          npm run build

      - name: Setup deployment
        run: |
          mkdir -p _site
          # Copy landing page from root
          cp index.html _site/
          # Copy 404 handler for SPA routing
          cp 404.html _site/
          # Copy PHI Helper backup
          cp phi-helper.html _site/
          cp style.css _site/
          cp chatbot.js _site/
          cp vendors.js _site/
          # Copy simple working version
          mkdir -p _site/bronxworks-simple
          cp -r bronxworks-simple/* _site/bronxworks-simple/
          # Copy production app
          mkdir -p _site/bronxworks-program-closure
          cp -r bronxworks-program-closure/dist/* _site/bronxworks-program-closure/
          # Copy POC
          mkdir -p _site/bronxworks-closeout-poc  
          cp -r bronxworks-closeout-poc/dist/* _site/bronxworks-closeout-poc/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4